//! This module implements an ICE (Interactive Connectivity Check) agent that can be used to establish a peer-to-peer connection.
//!
//! The implementation is based on RFC 8445.

const std = @import("std");
const stun = @import("stun");
const ice = @import("ice.zig");
const IfIterator = @import("if_iterator.zig");
const Messages = @import("messages.zig");
const ParsedServerUrl = @import("parsed_server_url.zig");
const TurnClient = @import("turn_client.zig");

const Core = @import("core.zig");

const Io = std.Io;
const Allocator = std.mem.Allocator;
const Socket = Io.net.Socket;
const IpAddress = Io.net.IpAddress;
const Candidate = ice.Candidate;
const Agent = @This();
const Logger = std.log.scoped(.ice);
const HostName = Io.net.HostName;

pub const max_message_size = 1500;

const connectivity_check_interval: std.Io.Duration = .fromMilliseconds(200);
const keep_alive_interval: std.Io.Duration = .fromSeconds(4);

/// Struct describing the configuration of the agent
pub const AgentConfig = struct {
    /// Local credentials of the agent (ufrag and password)
    ///
    /// Generated automatically if not provided
    credentials: ?ice.Credentials = null,
    /// Role of the agent in the ICE negotiation
    role: ice.Role = .controlling,
    /// List of ICE servers to use for gathering candidates.
    ///
    /// stuns/turns and turn with tcp are not supported. Malformed or unsupported servers will be ignored.
    ice_servers: []const ice.IceServer = &.{},
    /// Timeout in milliseconds before the agent considers the connection disconnected.
    disconnected_timeout: u32 = 5000,
    /// Timeout in milliseconds before the agent considers the connection failed.
    failed_timeout: u32 = 25000,
};

const Channel = union(enum) {
    socket: Socket,
    relay: *TurnClient,

    fn address(channel: Channel) IpAddress {
        return switch (channel) {
            .socket => |s| s.address,
            .relay => |c| c.socket.address,
        };
    }

    fn send(channel: Channel, agent: *Agent, dest: *const IpAddress, data: []const u8) !void {
        switch (channel) {
            .socket => |s| try s.send(agent.io, dest, data),
            .relay => |c| {
                const buffer = try agent.createPacket();
                defer agent.destroyPacket(buffer);
                try c.sendIndication(agent.io, buffer, dest.*, data);
            },
        }
    }

    fn eql(a: Channel, b: Channel) bool {
        return switch (a) {
            .socket => |s| switch (b) {
                .socket => |o| s.address.eql(&o.address),
                .relay => false,
            },
            .relay => |c| switch (b) {
                .relay => |o| c == o,
                .socket => false,
            },
        };
    }

    fn receiveTimeout(channel: Channel, io: Io, buffer: []u8, timeout: Io.Timeout) !struct { IpAddress, []const u8 } {
        switch (channel) {
            .socket => |s| {
                const incoming_message = try s.receiveTimeout(io, buffer, timeout);
                return .{ incoming_message.from, incoming_message.data };
            },
            .relay => |c| {
                const received = try c.receiveTimeout(io, buffer, timeout);
                return .{ received.from, received.data };
            },
        }
    }

    fn close(channel: Channel, io: Io) void {
        switch (channel) {
            .socket => |s| s.close(io),
            .relay => {},
        }
    }
};

const Message = struct {
    channel: Channel,
    incoming_message: Io.net.IncomingMessage,
};

const InnerEvent = union(enum) {
    message: Message,
    connectivity_check: void,
    app_data: []const u8,
    /// Add a new socket
    ///
    /// This is usually paired with a new server reflexive candidate
    add_socket: Socket,
    candidate: ?Candidate,
    close: void,
    complete: void,
    connection_state: ice.ConnectionState,
    gathering_state: ice.GatheringState,
};

// Timeouts config
disconnected_timeout: u32,
failed_timeout: u32,

io: Io,
core: Core,
ice_servers: []const ice.IceServer = &.{},
buffer_pool: std.heap.MemoryPool([max_message_size]u8),
sockets: std.ArrayList(Socket) = .empty,
relay_clients: std.ArrayList(*TurnClient) = .empty,

mutex: Io.Mutex = .init,
group: Io.Group = .init,
queue_buffer: []InnerEvent,
queue: Io.Queue(InnerEvent),
nominated_channel: ?Channel = null,

/// Event generated by the agent
pub const Event = union(enum) {
    /// Event describing a connection state change
    connection_state: ice.ConnectionState,
    /// Event describing a change in the gathering state of the agent
    gathering_state: ice.GatheringState,
    /// Event describing a new candidate discovered by the agent
    candidate: ?Candidate,
    /// Event describing a connectivity check message received by the agent.
    ///
    /// The data is owned by this agent and should be returned by calling `destroyPacket` function.
    data: []const u8,
};

pub fn init(io: Io, allocator: Allocator, config: AgentConfig) !Agent {
    var credens =
        try if (config.credentials) |credens|
            credens.dupe(allocator)
        else
            ice.Credentials.generate(io, allocator);
    errdefer credens.deinit(allocator);

    const queue_buffer = try allocator.alloc(InnerEvent, 10);

    return .{
        .disconnected_timeout = config.disconnected_timeout,
        .failed_timeout = config.failed_timeout,
        .io = io,
        .core = .init(allocator, config.role, credens, randomNumber(u64, io)),
        .ice_servers = config.ice_servers,
        .buffer_pool = .empty,
        .queue_buffer = queue_buffer,
        .queue = .init(queue_buffer),
    };
}

pub fn deinit(agent: *Agent) void {
    agent.closeConnection();
    agent.core.deinit();
    agent.buffer_pool.deinit(agent.core.allocator);
}

/// Poll the next event.
///
/// See the `Event` struct for the list of possible events.
/// The event `data` buffer is owned by the agent, after processing the data, the user should call `destroyPacket` to free the buffer.
pub fn poll(agent: *Agent) !Event {
    const io = agent.io;

    switch (agent.core.connection_state) {
        .failed, .closed => return error.FailedOrClosedAgent,
        else => {},
    }

    while (agent.queue.getOne(io)) |event| switch (event) {
        .add_socket => |socket| {
            errdefer socket.close(io);
            try agent.sockets.append(agent.core.allocator, socket);
            try agent.group.concurrent(io, receive, .{ agent, socket });
        },
        .candidate => |c| return .{ .candidate = c },
        .connectivity_check => agent.batchSendConnectivityCheck() catch |err| logError("connectivity check failed due to {}", .{err}),
        .message => |message| {
            const maybe_event = agent.handleConnectivityCheckMessage(message) catch |err| switch (err) {
                error.Canceled => return error.Canceled,
                error.SwitchRole => {
                    agent.mutex.lockUncancelable(io);
                    defer agent.mutex.unlock(io);
                    agent.core.toggleRole(randomNumber(u64, io));
                    continue;
                },
                else => continue,
            };

            if (maybe_event) |ev| return ev;
        },
        .app_data => |data| return .{ .data = data },
        .connection_state => |state| {
            if (state == .failed) agent.closeConnection();
            return .{ .connection_state = state };
        },
        .gathering_state => |state| {
            agent.core.gathering_state = state;
            return .{ .gathering_state = state };
        },
        .close => {
            agent.setConnectionState(.closed);
            agent.closeConnection();
            return .{ .connection_state = .closed };
        },
        .complete => {
            agent.setConnectionState(.completed);

            {
                agent.mutex.lockUncancelable(io);
                defer agent.mutex.unlock(io);
                agent.core.onComplete();
            }
            agent.pruneNonNominatedRelayClients();

            return .{ .connection_state = .completed };
        },
    } else |err| return err;
}

pub fn getRole(agent: *const Agent) ice.Role {
    return agent.core.role;
}

/// Set the role of the agent in the ICE negotiation.
pub fn setRole(agent: *Agent, role: ice.Role) void {
    agent.mutex.lockUncancelable(agent.io);
    defer agent.mutex.unlock(agent.io);
    if (agent.core.role == role) return;
    agent.core.toggleRole(randomNumber(u64, agent.io));
}

/// Set remote credentials
///
/// Calling this function will trigger connectivity checks. `gatherCandidates` should be called first.
pub fn setRemoteCredentials(agent: *Agent, credentials: ice.Credentials) !void {
    switch (agent.core.connection_state) {
        .new => {
            const credens = try credentials.dupe(agent.core.allocator);
            if (agent.core.remote_credentials == null) {
                try agent.group.concurrent(agent.io, connectivityCheck, .{ agent, connectivity_check_interval });
            }
            agent.core.remote_credentials = credens;
            agent.setConnectionState(.checking);
        },
        else => return error.CredentialsAlreadySet,
    }
}

pub fn localCredentials(agent: *const Agent) ice.Credentials {
    return agent.core.credentials;
}

pub fn remoteCredentials(agent: *const Agent) ?ice.Credentials {
    return agent.core.remote_credentials;
}

pub fn localCandidates(agent: *const Agent) []Candidate {
    return agent.core.candidates.items;
}

pub fn gatheringState(agent: *const Agent) ice.GatheringState {
    return agent.core.gathering_state;
}

pub fn connectionState(agent: *const Agent) ice.ConnectionState {
    return agent.core.connection_state;
}

pub fn addRemoteCandidate(agent: *Agent, remote_candidate: Candidate) !void {
    switch (agent.core.connection_state) {
        .new, .checking, .connected => {
            agent.mutex.lockUncancelable(agent.io);
            defer agent.mutex.unlock(agent.io);
            try agent.core.addRemoteCandidate(remote_candidate);
        },
        else => {},
    }
}

/// Start gathering candidates.
///
/// This function should be called first before starting the event loop so local sockets are
/// available to listen on.
pub fn gatherCandidates(agent: *Agent) !void {
    try agent.putInQueue(.{ .gathering_state = .gathering });
    try agent.gatherLocalHostsAndInitSockets();

    for (agent.core.candidates.items) |candidate| {
        try agent.queue.putOne(agent.io, .{ .candidate = candidate });
    }

    for (agent.sockets.items) |socket| {
        try agent.group.concurrent(agent.io, receive, .{ agent, socket });
    }

    if (agent.ice_servers.len != 0) {
        try agent.group.concurrent(agent.io, gatherServerReflexiveCandidates, .{agent});
    } else {
        try agent.queue.putOne(agent.io, .{ .candidate = null });
        try agent.putInQueue(.{ .gathering_state = .complete });
    }
}

pub fn sendData(agent: *Agent, data: []const u8) !void {
    switch (agent.core.connection_state) {
        .connected, .completed => {
            @branchHint(.likely);
            const dest = &agent.core.nominated_pair.?.remote;
            try agent.nominated_channel.?.send(agent, &dest.address, data);
        },
        else => Logger.warn("Agent not connected: ignore send request", .{}),
    }
}

/// Gets a buffer from the pool to be used for sending or receiving data.
pub fn createPacket(agent: *Agent) Allocator.Error![]u8 {
    agent.mutex.lockUncancelable(agent.io);
    defer agent.mutex.unlock(agent.io);
    return try agent.buffer_pool.create(agent.core.allocator);
}

/// Free the buffer and return it to the pool.
pub fn destroyPacket(agent: *Agent, data: []const u8) void {
    agent.mutex.lockUncancelable(agent.io);
    defer agent.mutex.unlock(agent.io);
    agent.buffer_pool.destroy(@ptrCast(@alignCast(@constCast(data))));
}

/// Close the agent connection
///
/// This function will only enqueue an event that'll be handled
/// by the inner queue. The user will get connection state update.
pub fn close(agent: *Agent) void {
    agent.queue.putOneUncancelable(agent.io, .close) catch {};
}

fn closeConnection(agent: *Agent) void {
    const allocator = agent.core.allocator;

    agent.group.cancel(agent.io);
    allocator.free(agent.queue_buffer);
    agent.queue_buffer = &.{};

    agent.sockets.clearAndFree(allocator);

    for (agent.relay_clients.items) |client| {
        client.deinit(agent.io);
        allocator.destroy(client);
    }
    agent.relay_clients.clearAndFree(allocator);
    _ = agent.buffer_pool.reset(allocator, .free_all);
}

fn gatherLocalHostsAndInitSockets(agent: *Agent) !void {
    const allocator = agent.core.allocator;

    var it: IfIterator = try .init(allocator);
    defer it.deinit(allocator);
    errdefer for (agent.sockets.items) |*socket| socket.close(agent.io);

    while (it.next()) |addr| {
        const socket = addr.bind(agent.io, .{ .mode = .dgram }) catch |err| {
            Logger.warn("Could not bind address {f}: {}", .{ addr, err });
            continue;
        };

        agent.mutex.lockUncancelable(agent.io);
        defer agent.mutex.unlock(agent.io);

        try agent.sockets.append(allocator, socket);
        _ = try agent.core.addHostCandidate(socket.address);
    }
}

fn gatherServerReflexiveCandidates(agent: *Agent) Io.Cancelable!void {
    agent.doGatherServerReflexiveCandidates() catch |err| switch (err) {
        error.Canceled => return error.Canceled,
        else => {},
    };
}

fn doGatherServerReflexiveCandidates(agent: *Agent) !void {
    const io = agent.io;

    var grp: Io.Group = .init;
    var q_buffer: [16]HostName.LookupResult = undefined;

    for (agent.ice_servers) |ice_server| {
        var q = Io.Queue(HostName.LookupResult).init(&q_buffer);
        const parsed = ParsedServerUrl.parse(ice_server.url) catch |err| {
            Logger.warn("Invalid ice server url: {s}, err: {}", .{ ice_server.url, err });
            continue;
        };

        if (std.Io.net.IpAddress.resolve(io, parsed.host, parsed.port)) |addr| {
            try q.putOne(io, .{ .address = addr });
            q.close(io);
        } else |_| {
            var hostname = HostName.init(parsed.host) catch continue;
            hostname.lookup(io, &q, .{ .port = parsed.port }) catch |err| switch (err) {
                error.Canceled => return error.Canceled,
                else => {
                    Logger.warn("Failed to resolve ice server hostname: {s}", .{parsed.host});
                    continue;
                },
            };
        }

        while (q.getOne(io)) |result| switch (result) {
            .address => |addr| {
                if (std.meta.activeTag(addr) == .ip6) continue;
                try grp.concurrent(io, sendBindingRequest, .{ agent, addr });
                if (parsed.scheme == .turn) {
                    try grp.concurrent(io, trunAllocate, .{ agent, addr, ice_server.username, ice_server.credential });
                }
            },
            else => {},
        } else |_| {}
    }

    try grp.await(io);
    try agent.putInQueue(.{ .candidate = null });
    try agent.putInQueue(.{ .gathering_state = .complete });
}

fn sendBindingRequest(agent: *Agent, dest: IpAddress) !void {
    const socket = (IpAddress{ .ip4 = .unspecified(0) }).bind(
        agent.io,
        .{ .mode = .dgram },
    ) catch return;
    errdefer socket.close(agent.io);

    const tx_id: u96 = randomNumber(u96, agent.io);
    var rto: u16 = 500;
    var attempts: u8 = 5;
    var timeout = Io.Timeout{ .duration = .{ .clock = .awake, .raw = .fromMilliseconds(rto) } };

    const buffer = agent.createPacket() catch return;
    defer agent.destroyPacket(buffer);

    while (attempts > 0) : (attempts -= 1) {
        const req = Messages.builUnauthenticatedBindingRequest(buffer, tx_id) catch unreachable;

        socket.send(agent.io, &dest, req) catch |err| switch (err) {
            error.Canceled => return error.Canceled,
            else => |e| {
                Logger.warn("Failed to send binding request to {f}: {}", .{ dest, e });
                continue;
            },
        };

        const incoming_msg = socket.receiveTimeout(agent.io, buffer, timeout) catch |err| switch (err) {
            error.Timeout => {
                rto = rto * 2 + 500;
                timeout.duration.raw = .fromMilliseconds(rto);
                continue;
            },
            error.Canceled => return error.Canceled,
            else => return,
        };

        const addr = Messages.getMappedAddress(incoming_msg.data, tx_id) catch continue;

        const candidate = blk: {
            agent.mutex.lockUncancelable(agent.io);
            defer agent.mutex.unlock(agent.io);
            break :blk agent.core.addServerReflexiveCandidate(socket.address, addr) catch {
                socket.close(agent.io);
                return;
            };
        } orelse {
            socket.close(agent.io);
            return;
        };
        try agent.putInQueue(.{ .add_socket = socket });
        try agent.putInQueue(.{ .candidate = candidate });
        return;
    }
}

fn trunAllocate(agent: *Agent, dest: IpAddress, username: []const u8, pass: []const u8) !void {
    agent.doTrunAllocate(dest, username, pass) catch |err| switch (err) {
        error.Canceled => return error.Canceled,
        else => {
            Logger.warn("Failed to allocate turn relay: {}", .{err});
            return;
        },
    };
}

fn doTrunAllocate(agent: *Agent, dest: IpAddress, username: []const u8, pass: []const u8) !void {
    const io = agent.io;
    const allocator = agent.core.allocator;

    const client: *TurnClient = blk: {
        const socket = try (IpAddress{ .ip4 = .unspecified(0) }).bind(io, .{ .mode = .dgram });
        errdefer socket.close(io);

        const client = try allocator.create(TurnClient);
        errdefer allocator.destroy(client);

        client.* = TurnClient.init(allocator, .{
            .socket = socket,
            .server = dest,
            .username = username,
            .password = pass,
        });
        break :blk client;
    };
    errdefer client.deinit(io);

    try client.group.concurrent(io, relayReceive, .{ agent, client, io });

    const buffer = try agent.createPacket();
    defer agent.destroyPacket(buffer);

    Logger.debug("Create allocation: {f}", .{dest});
    const allocation_result = try client.createAllocation(io, buffer);
    const candidate = ice.Candidate.initRelay(client.socket.address, allocation_result.relayed_address);

    {
        agent.mutex.lockUncancelable(io);
        defer agent.mutex.unlock(io);
        _ = try agent.core.addLocalCandidate(candidate);
    }
    try agent.putInQueue(.{ .candidate = candidate });

    agent.mutex.lockUncancelable(io);
    defer agent.mutex.unlock(io);
    try agent.relay_clients.append(allocator, client);
}

fn relayReceive(agent: *Agent, client: *TurnClient, io: Io) !void {
    agent.doRelayReceive(client, io) catch |err| switch (err) {
        error.Canceled => return error.Canceled,
        else => |e| logError("Error when receiving from turn client: {}", .{e}),
    };
}

fn doRelayReceive(agent: *Agent, client: *TurnClient, io: Io) !void {
    while (true) {
        switch (agent.core.connection_state) {
            .completed => {
                if (agent.isNominatedChannel(.{ .relay = client }))
                    try agent.group.concurrent(io, receiveAppData, .{ agent, Channel{ .relay = client } });
                return;
            },
            .failed, .closed => return,
            else => {},
        }

        const buffer = try agent.createPacket();
        errdefer agent.destroyPacket(buffer);

        const received = try client.receive(io, buffer);

        try agent.putInQueue(.{
            .message = .{
                .channel = .{ .relay = client },
                .incoming_message = .{
                    .from = received.from,
                    .data = @constCast(received.data),
                    .control = &.{},
                    .flags = @bitCast(@as(u8, 0)),
                },
            },
        });
    }
}

fn randomNumber(T: type, io: Io) T {
    var bytes: [@typeInfo(T).int.bits / 8]u8 = undefined;
    io.random(&bytes);
    return @bitCast(bytes);
}

fn findSocket(agent: *Agent, addr: *const IpAddress) ?*Io.net.Socket {
    for (agent.sockets.items) |*socket| if (socket.address.eql(addr)) return socket;
    return null;
}

fn findRelayClient(agent: *Agent, addr: *const IpAddress) ?*TurnClient {
    for (agent.relay_clients.items) |client| if (client.socket.address.eql(addr)) return client;
    return null;
}

fn ensurePermission(agent: *Agent, client: *TurnClient, peer: IpAddress, buffer: []u8) !void {
    if (client.hasPermission(peer)) return;
    try client.createPermissionsSlice(agent.io, buffer, &.{peer});
}

fn isNominatedChannel(agent: *Agent, channel: Channel) bool {
    const nominated = agent.nominated_channel orelse return false;
    return nominated.eql(channel);
}

fn pruneNonNominatedRelayClients(agent: *Agent) void {
    const allocator = agent.core.allocator;

    var i: usize = 0;
    while (i < agent.relay_clients.items.len) {
        const client = agent.relay_clients.items[i];
        if (agent.isNominatedChannel(.{ .relay = client })) {
            i += 1;
            continue;
        }

        client.deinit(agent.io);
        allocator.destroy(client);
        _ = agent.relay_clients.swapRemove(i);
    }
}

fn setConnectionState(agent: *Agent, new_state: ice.ConnectionState) void {
    agent.core.connection_state = new_state;
}

fn connectivityCheck(agent: *Agent, timeout: Io.Duration) !void {
    var dur = Io.Duration{ .nanoseconds = 0 };
    const failed_timeout = Io.Duration.fromMilliseconds(agent.failed_timeout);

    while (true) {
        switch (agent.core.connection_state) {
            .completed, .failed, .closed => return,
            else => |state| {
                try agent.io.sleep(timeout, .awake);
                dur.nanoseconds += timeout.nanoseconds;
                if (state != .connected and dur.nanoseconds > failed_timeout.nanoseconds) {
                    agent.setConnectionState(.failed);
                    try agent.putInQueue(.{ .connection_state = .failed });
                    return;
                }
                try agent.putInQueue(.{ .connectivity_check = {} });
            },
        }
    }
}

fn receive(agent: *Agent, socket: Socket) !void {
    agent.doReceive(&socket) catch |err| switch (err) {
        error.Canceled => return error.Canceled,
        else => |e| logError("Error when receiving: {}", .{e}),
    };
}

fn doReceive(agent: *Agent, socket: *const Socket) !void {
    const io = agent.io;
    const timeout: Io.Timeout = .{ .duration = .{ .clock = .awake, .raw = .fromSeconds(2) } };
    errdefer socket.close(io);

    while (true) {
        switch (agent.core.connection_state) {
            .completed => {
                if (agent.isNominatedChannel(.{ .socket = socket.* }))
                    try agent.group.concurrent(io, receiveAppData, .{ agent, Channel{ .socket = socket.* } })
                else
                    socket.close(io);
                return;
            },
            .failed, .closed => {
                socket.close(io);
                return;
            },
            else => {},
        }

        var result: Message = .{ .channel = .{ .socket = socket.* }, .incoming_message = undefined };

        const buffer = try agent.createPacket();
        result.incoming_message = socket.receiveTimeout(agent.io, buffer, timeout) catch |err| {
            agent.destroyPacket(buffer);
            switch (err) {
                // We provide timeout to allow checking the agent status to close this socket
                // if it's no longer needed
                error.Timeout => continue,
                else => |e| return e,
            }
        };

        try agent.putInQueue(.{ .message = result });
    }
}

fn receiveAppData(agent: *Agent, channel: Channel) !void {
    var timeout: Io.Timeout = .{ .duration = .{ .clock = .awake, .raw = .fromMilliseconds(agent.disconnected_timeout) } };
    defer channel.close(agent.io);

    while (true) {
        const buffer = agent.createPacket() catch return;

        const from, const data = channel.receiveTimeout(agent.io, buffer, timeout) catch |err| {
            agent.destroyPacket(buffer);

            switch (err) {
                error.Timeout => {
                    const new_state = agent.core.onConsentTimeout() orelse return;
                    try agent.putInQueue(.{ .connection_state = new_state });
                    if (new_state != .disconnected) return; // .failed
                    timeout.duration.raw = .fromMilliseconds(agent.failed_timeout);
                    continue;
                },
                error.Canceled => return error.Canceled,
                else => |e| {
                    logError("Error when listening: {}", .{e});
                    return;
                },
            }
        };

        if (agent.core.connection_state == .disconnected) {
            @branchHint(.cold);
            timeout.duration.raw = .fromMilliseconds(agent.disconnected_timeout);
            agent.setConnectionState(.completed);
            try agent.putInQueue(.{ .connection_state = .completed });
        }

        if (stun.isMessage(data)) {
            defer agent.destroyPacket(data);
            agent.handleConsentFreshness(&from, data) catch continue;
        } else try agent.putInQueue(.{ .app_data = data });
    }
}

fn keepAlive(agent: *Agent, timeout: Io.Duration) !void {
    const io = agent.io;
    while (true) {
        try io.sleep(timeout, .awake);
        agent.sendConsentFreshness() catch return;
    }
}

fn sendConsentFreshness(agent: *Agent) !void {
    var buffer: [256]u8 = undefined;
    const req = try agent.core.buildBindingRequest(randomNumber(u96, agent.io), false, &buffer);
    const remote_candidate = &agent.core.nominated_pair.?.remote;
    try agent.nominated_channel.?.send(agent, &remote_candidate.address, req);
}

fn putInQueue(agent: *Agent, event: InnerEvent) !void {
    agent.queue.putOne(agent.io, event) catch |in_err| switch (in_err) {
        error.Canceled => return error.Canceled,
        else => {},
    };
}

fn batchSendConnectivityCheck(agent: *Agent) !void {
    var checks = agent.core.beginConnectivityChecks() orelse return;

    var buffer: [max_message_size]u8 = undefined;
    var indication_buffer: [max_message_size]u8 = undefined;
    while (try checks.next(&buffer, randomNumber(u96, agent.io))) |send| {
        if (agent.findRelayClient(&send.from_base)) |client| {
            agent.ensurePermission(client, send.to, &indication_buffer) catch |err| {
                Logger.warn("Failed to create turn permission for {f}: {}", .{ send.to, err });
                continue;
            };

            if (send.use_candidate) agent.nominated_channel = .{ .relay = client };

            client.sendIndication(agent.io, &indication_buffer, send.to, send.payload) catch |err| {
                Logger.warn("Failed to send binding request via relay to {f}: {}", .{ send.to, err });
            };
            continue;
        }

        const socket = agent.findSocket(&send.from_base) orelse continue;
        if (send.use_candidate) agent.nominated_channel = .{ .socket = socket.* };

        Logger.debug("Send binding request to {f} (use_candidate={})", .{ send.to, send.use_candidate });
        socket.send(agent.io, &send.to, send.payload) catch |err| {
            Logger.warn("Failed to send binding request to {f}: {}", .{ send.to, err });
        };
    }
}

fn handleConnectivityCheckMessage(agent: *Agent, message: Message) !?Event {
    const data = message.incoming_message.data;
    const sender = message.incoming_message.from;

    if (stun.isMessage(data)) {
        defer agent.destroyPacket(data);
        switch (agent.core.connection_state) {
            .completed, .failed, .closed => return null, // sockets are closed
            else => {},
        }

        const msg = try stun.Message.parse(data);

        switch (msg.header.message_type.class()) {
            .request => {
                const buffer = try agent.createPacket();
                defer agent.destroyPacket(buffer);

                const resp = res: {
                    agent.mutex.lockUncancelable(agent.io);
                    defer agent.mutex.unlock(agent.io);

                    const r = try agent.core.handleRequest(&msg, message.channel.address(), sender, buffer);
                    if (agent.core.detectNominatedPair() != null) agent.nominated_channel = message.channel;

                    break :res r;
                };

                try message.channel.send(agent, &sender, resp);
            },
            .success_response => {
                agent.mutex.lockUncancelable(agent.io);
                defer agent.mutex.unlock(agent.io);
                try agent.core.handleSuccessResponse(&msg, message.channel.address(), sender);
                if (agent.core.detectNominatedPair() != null) agent.nominated_channel = message.channel;
            },
            else => {},
        }

        if (agent.core.markConnected()) {
            const io = agent.io;

            try agent.group.concurrent(io, markConnectionCompleted, .{ agent, .fromSeconds(5) });
            try agent.group.concurrent(io, keepAlive, .{ agent, keep_alive_interval });
            return .{ .connection_state = agent.core.connection_state };
        }
    } else {
        switch (agent.core.connection_state) {
            .connected, .completed => return .{ .data = data },
            else => {
                for (agent.core.pairs.items) |*candidate_pair| {
                    const remote = &agent.core.remote_candidates.items[candidate_pair.remote];
                    if (remote.address.eql(&sender)) return .{ .data = data };
                } else {
                    agent.destroyPacket(data);
                    Logger.warn("Drop non stun message from unknown remote candidate: {f}", .{sender});
                }
            },
        }
    }

    return null;
}

fn handleConsentFreshness(agent: *Agent, from: *const IpAddress, data: []const u8) !void {
    Logger.debug("Received consent freshness request", .{});
    const buffer = try agent.createPacket();
    defer agent.destroyPacket(buffer);

    if (try agent.core.handleConsentFreshness(from, data, buffer)) |resp| {
        try agent.nominated_channel.?.send(agent, from, resp);
    }
}

fn markConnectionCompleted(agent: *Agent, timeout: Io.Duration) !void {
    try agent.io.sleep(timeout, .awake);
    try agent.putInQueue(.complete);
}

fn logError(comptime fmt: []const u8, args: anytype) void {
    if (!builtin.is_test) {
        Logger.err(fmt, args);
    } else {
        Logger.warn(fmt, args);
    }
}

const builtin = @import("builtin");
const testing = std.testing;

fn testNewAgent() !Agent {
    return try .init(testing.io, testing.allocator, .{ .role = .controlled });
}

test "init agent" {
    {
        var agent: Agent = try .init(testing.io, testing.allocator, .{});
        defer agent.deinit();
    }

    {
        var failing_alloc = testing.FailingAllocator.init(testing.allocator, .{ .fail_index = 2 });
        try testing.expectError(
            error.OutOfMemory,
            Agent.init(testing.io, failing_alloc.allocator(), .{}),
        );
    }
}

test "randomNumber" {
    const a = randomNumber(u64, testing.io);
    const b = randomNumber(u64, testing.io);
    const c = randomNumber(u64, testing.io);

    try testing.expect(a != b);
    try testing.expect(b != c);
    try testing.expect(a != c);
}

test "close" {
    var agent = try testNewAgent();
    defer agent.deinit();

    var grp: Io.Group = .init;
    defer grp.cancel(testing.io);

    var close_event: Io.Event = .unset;

    const closeAgent = struct {
        pub fn close(a: *Agent) !void {
            try a.io.sleep(.fromMilliseconds(100), .awake);
            a.close();
        }
    }.close;

    const polling = struct {
        pub fn poll(a: *Agent, event: *Io.Event) !void {
            while (a.poll()) |ev| switch (ev) {
                .connection_state => |state| switch (state) {
                    .closed => event.set(a.io),
                    else => {},
                },
                else => {},
            } else |_| return;
        }
    }.poll;

    try grp.concurrent(testing.io, polling, .{ &agent, &close_event });
    try agent.gatherCandidates();
    try agent.setRemoteCredentials(.{ .username = "user", .password = "password" });

    try grp.concurrent(testing.io, closeAgent, .{&agent});

    close_event.waitTimeout(testing.io, .{ .duration = .{ .raw = .fromSeconds(1), .clock = .awake } }) catch {
        return error.FailedTest;
    };
}
